# Generated by Django 3.2.11 on 2022-01-19 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='headlines',
            new_name='headline',
        ),
    ]
